---
- name: Install and start qemu-guest-agent
  hosts: prem_vm_ubuntu
  become: true
  ignore_unreachable: true
  tasks:
    - name: apt install
      apt:
        name: qemu-guest-agent
        state: present
        force_apt_get: yes
        update_cache: yes
    - name: systemctl start
      systemd:
        name: qemu-guest-agent
        state: started
        enabled: yes
