---
- name: Update all packages
  hosts:
    - ubuntu
  become: true
  ignore_unreachable: true
  serial:
    - 1
  tasks:
    - name: apt install needrestart
      apt:
        name: needrestart
        state: present
        force_apt_get: yes
        update_cache: yes
    - name: apt update
      apt:
        upgrade: dist
        force_apt_get: yes
        update_cache: yes
        autoremove: yes
- name: Restart services
  hosts:
    - ubuntuvms
    - ubuntucts
  serial:
    - 1
  tasks:
    - name: Restart services automatically
      shell:
        cmd: needrestart -r a
      ignore_errors: true
