---
- name: Deploy apt proxy config
  hosts:
    - prem_ubuntu
  become: true
  ignore_unreachable: true
  tasks:
    - name: Install apt proxy config
      copy:
        dest: /etc/apt/apt.conf.d/99-proxy.conf
        owner: root
        group: root
        content: |
          Acquire::http::proxy "http://192.0.2.100:3142";
